name: Runner

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: false

concurrency:
  group: ${{ github.ref }}

jobs:
  runner:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          path: main

      - uses: actions/checkout@v4
        with:
          ref: icons
          path: icons

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: "latest"

      - name: Prepare environment
        run: mkdir tmp

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install PNPM deps
        run: |
          npm i -g pnpm
          pnpm i --prod

      - name: Download hermes-dec
        working-directory: tmp
        run: git clone https://github.com/P1sec/hermes-dec

      - name: Download latest Discord APK
        working-directory: tmp
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            version=`curl -s "https://vd.k6.tf/tracker/index" | grep -o '"alpha":[0-9]*' | grep -o '[0-9]*'`
          else
            version="${{ github.event.inputs.version }}"
          fi
          echo version=$version >> $GITHUB_ENV

          curl -o discord_base.zip -L https://vd.k6.tf/tracker/download/$version/base
          curl -o discord_xxhdpi.zip -L https://vd.k6.tf/tracker/download/$version/config.xxhdpi

          mkdir discordapk

          unzip discord_base -d discordapk/base
          unzip discord_xxhdpi -d discordapk/xxhdpi

          rm discord_base.zip
          rm discord_xxhdpi.zip

      - name: Use hermes to decompile Discord APK
        working-directory: tmp
        run: python hermes-dec/hbc_decompiler.py discordapk/base/assets/index.android.bundle decompiled.js

      - name: Parse colors (1/2)
        working-directory: main
        env:
          webhookURL: ${{ secrets.VENDETTA_WEBHOOK }}
        run: |
          node scripts/colors/parser.js $version action

          git add colors

          node --no-warnings scripts/colors/sender.js $webhookURL

          cd tmp
          node ../scripts/writecommit.js colors
          msg=`cat commit.txt`
          git commit -m "$msg" | true

      - name: Parse icons (2/2)
        working-directory: main
        run: |
          node scripts/icons/parser.js $version action

          git add icons -f

          cd tmp
          node ../scripts/writecommit.js icons
          msg=`cat commit.txt`
          git commit -m "$msg" | true

      - name: Commit changes
        run: git push
