name: Testing

on: workflow_dispatch

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Test 1
        run: echo test="12346546547897897" >> $GITHUB_ENV

      - name: Test 2
        run: echo $test
