name: Testing

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: false

jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Test 1
        run: echo test="${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Test 2
        run: echo $test
